/** @format */

const express = require("express")
const router = express.Router()

// Controllers
const Admin = require("./Admin")
const BlogPic = require("./BlogPic")
const BlogPost = require("./BlogPost")
const Brochure_EndFormat = require("./Brochure_EndFormat")
const Brochure_Material = require("./Brochure_Material")
const Button_EndFormat = require("./Button_EndFormat")
const Cart = require("./Cart")
const Category = require("./Category")
const ConstantShipment = require("./ConstantShipment")
const CustomForm_Etiketten = require("./CustomForm_Etiketten")
const EndFormat_Etiketten = require("./EndFormat_Etiketten")
const FolderEin_EndFormat = require("./FolderEin_EndFormat")
const FrontPages = require("./FrontPages")
const Image = require("./Image")
const Invoice = require("./Invoice")
const Material_Etiketten = require("./Material_Etiketten")
const OrderStatus = require("./OrderStatus")
const Poster_EndFormat = require("./Poster_EndFormat")
const Poster_Material = require("./Poster_Material")
const PrintyDatumstempel_Art = require("./PrintyDatumstempel_Art")
const PrintyDatumstempel_PillowColor = require("./PrintyDatumstempel_PillowColor")
const Product = require("./Product")
const RollUp_EndFormat = require("./RollUp_EndFormat")
const RollUp_Material = require("./RollUp_Material")
const Shape_Etiketten = require("./Shape_Etiketten")
const Test = require("../../panel/v1/Test")
const Visitenkarte_Klapp_EndFormat = require("./Visitenkarte_Klapp_EndFormat")
const Visitenkarte_Standard_EndFormat = require("./Visitenkarte_Standard_EndFormat")

const BaseController = require("../../../controller/BaseController")
const Controller = new BaseController()

// version 1 of app

router.use("/Admin", Admin)
router.use("/BlogPic", BlogPic)
router.use("/BlogPost", BlogPost)
router.use("/Brochure_EndFormat", Brochure_EndFormat)
router.use("/Brochure_Material", Brochure_Material)
router.use("/Button_EndFormat", Button_EndFormat)
router.use("/Cart", Cart)
router.use("/Category", Category)
router.use("/ConstantShipment", ConstantShipment)
router.use("/CustomForm_Etiketten", CustomForm_Etiketten)
router.use("/EndFormat_Etiketten", EndFormat_Etiketten)
router.use("/FolderEin_EndFormat", FolderEin_EndFormat)
router.use("/FrontPages", FrontPages)
router.use("/Image", Image)
router.use("/Invoice", Invoice)
router.use("/Material_Etiketten", Material_Etiketten)
router.use("/OrderStatus", OrderStatus)
router.use("/Poster_EndFormat", Poster_EndFormat)
router.use("/Poster_Material", Poster_Material)
router.use("/PrintyDatumstempel_Art", PrintyDatumstempel_Art)
router.use("/PrintyDatumstempel_PillowColor", PrintyDatumstempel_PillowColor)
router.use("/Product", Product)
router.use("/RollUp_EndFormat", RollUp_EndFormat)
router.use("/RollUp_Material", RollUp_Material)
router.use("/Shape_Etiketten", Shape_Etiketten)
router.use("/Test", Test)
router.use("/Visitenkarte_Klapp_EndFormat", Visitenkarte_Klapp_EndFormat)
router.use("/Visitenkarte_Standard_EndFormat", Visitenkarte_Standard_EndFormat)

router.post("/initialize", Controller.initialize.bind(Controller))
router.post("/endFormatFixer", Controller.endFormatFixer.bind(Controller))

module.exports = router
