/** @format */

const express = require("express")
const router = express.Router()

const Address = require("./Address")
const BlogPost = require("./BlogPost")
const Brochure_EndFormat = require("./Brochure_EndFormat")
const Brochure_Material = require("./Brochure_Material")
const Brochure_Record = require("./Brochure_Record")
const Button_EndFormat = require("./Button_EndFormat")
const Button_Record = require("./Button_Record")
const Cart = require("./Cart")
const Category = require("./Category")
const Complaint = require("./Complaint")
const ConstantShipment = require("./ConstantShipment")
const CustomForm_Etiketten = require("./CustomForm_Etiketten")
const DigiPrint_Material = require("./DigiPrint_Material")
const EndFormat_Etiketten = require("./EndFormat_Etiketten")
const EndFormat_Flyer = require("./EndFormat_Flyer")
const FlyerRecord = require("./FlyerRecord")
const FolderEin_EndFormat = require("./FolderEin_EndFormat")
const FrontPages = require("./FrontPages")
const FolderEin_Record = require("./FolderEin_Record")
const FolderWickelfalz6seiten_EndFormat = require("./FolderWickelfalz6seiten_EndFormat")
const FolderWickelfalz6seiten_Record = require("./FolderWickelfalz6seiten_Record")
const FolderWickelfalz8seiten_EndFormat = require("./FolderWickelfalz8seiten_EndFormat")
const FolderWickelfalz8seiten_Record = require("./FolderWickelfalz8seiten_Record")
const FolderZfalz6Seiten_EndFormat = require("./FolderZfalz6Seiten_EndFormat")
const FolderZfalz6Seiten_Record = require("./FolderZfalz6Seiten_Record")
const FolderZfalz8Seiten_EndFormat = require("./FolderZfalz8Seiten_EndFormat")
const FolderZfalz8Seiten_Record = require("./FolderZfalz8Seiten_Record")
const Image = require("./Image")
const Lesezeichen_EndFormat = require("./Lesezeichen_EndFormat")
const Lesezeichen_Material = require("./Lesezeichen_Material")
const Lesezeichen_Record = require("./Lesezeichen_Record")
const Material_Etiketten = require("./Material_Etiketten")
const Material_Klebe_Buchstabe = require("./Material_Klebe_Buchstabe")
const Nodemailer = require("./Nodemailer")
const Order = require("./Order")
const Package = require("./Package")
const Poster_EndFormat = require("./Poster_EndFormat")
const Poster_Record = require("./Poster_Record")
const PrintyDatumstempel_PillowColor = require("./PrintyDatumstempel_PillowColor")
const PrintyDatumstempel_Record = require("./PrintyDatumstempel_Record")
const Product = require("./Product")
const RollUp_EndFormat = require("./RollUp_EndFormat")
const RollUp_Record = require("./RollUp_Record")
const Shape_Etiketten = require("./Shape_Etiketten")
const Support = require("./Support")
const Test_Record = require("./Test_Record")
const User = require("./User")

// version 1 of app
router.use("/Address", Address)
router.use("/BlogPost", BlogPost)
router.use("/Brochure_EndFormat", Brochure_EndFormat)
router.use("/Brochure_Material", Brochure_Material)
router.use("/Brochure_Record", Brochure_Record)
router.use("/Button_EndFormat", Button_EndFormat)
router.use("/Button_Record", Button_Record)
router.use("/Cart", Cart)
router.use("/Category", Category)
router.use("/Complaint", Complaint)
router.use("/ConstantShipment", ConstantShipment)
router.use("/CustomForm_Etiketten", CustomForm_Etiketten)
router.use("/DigiPrint_Material", DigiPrint_Material)
router.use("/EndFormat_Etiketten", EndFormat_Etiketten)
router.use("/EndFormat_Flyer", EndFormat_Flyer)
router.use("/FlyerRecord", FlyerRecord)
router.use("/FolderEin_EndFormat", FolderEin_EndFormat)
router.use("/FolderEin_Record", FolderEin_Record)
router.use("/FrontPages", FrontPages)
router.use("/FolderWickelfalz6seiten_EndFormat", FolderWickelfalz6seiten_EndFormat)
router.use("/FolderWickelfalz6seiten_Record", FolderWickelfalz6seiten_Record)
router.use("/FolderWickelfalz8seiten_EndFormat", FolderWickelfalz8seiten_EndFormat)
router.use("/FolderWickelfalz8seiten_Record", FolderWickelfalz8seiten_Record)
router.use("/FolderZfalz6Seiten_EndFormat", FolderZfalz6Seiten_EndFormat)
router.use("/FolderZfalz6Seiten_Record", FolderZfalz6Seiten_Record)
router.use("/FolderZfalz8Seiten_EndFormat", FolderZfalz8Seiten_EndFormat)
router.use("/FolderZfalz8Seiten_Record", FolderZfalz8Seiten_Record)
router.use("/Image", Image)
router.use("/Lesezeichen_EndFormat", Lesezeichen_EndFormat)
router.use("/Lesezeichen_Material", Lesezeichen_Material)
router.use("/Lesezeichen_Record", Lesezeichen_Record)
router.use("/Material_Etiketten", Material_Etiketten)
router.use("/Material_Klebe_Buchstabe", Material_Klebe_Buchstabe)
router.use("/Nodemailer", Nodemailer)
router.use("/Order", Order)
router.use("/Package", Package)
router.use("/Poster_EndFormat", Poster_EndFormat)
router.use("/Poster_Record", Poster_Record)
router.use("/PrintyDatumstempel_PillowColor", PrintyDatumstempel_PillowColor)
router.use("/PrintyDatumstempel_Record", PrintyDatumstempel_Record)
router.use("/Product", Product)
router.use("/RollUp_EndFormat", RollUp_EndFormat)
router.use("/RollUp_Record", RollUp_Record)
router.use("/Shape_Etiketten", Shape_Etiketten)
router.use("/Support", Support)
router.use("/Test_Record", Test_Record)
router.use("/User", User)

module.exports = router
